<?php
/**
 * Group Grade Base
 */

use Illuminate\Database\Capsule\Manager as Capsule;

/**
 * Loading of the system
 *
 * @access private
 */
function groupgrade_init() {
  // Composer
  if (! file_exists(__DIR__.'/vendor/autoload.php'))
    die('Composer is not setup for Groupgrade.
      You need to run "drush dl composer && drush composer install"');

  // Load Composer Dependencies
  require_once __DIR__.'/vendor/autoload.php';
  
  Drupal\ClassLearning\Common\Database::setupCapsule();
  
}

function groupgrade_menu() {
  // Parent Level Menu
  
  $frontend = require(__DIR__.'/Menus/Frontend.php');
  $admin = require(__DIR__.'/Menus/Admin.php');

  return array_merge($frontend, $admin);
}


/**
 * Change the administration menu content before it is rendered.
 *
 * @param $content: A structured array suitable for drupal_render(), containing:
 *       menu: The administrative menu of links below the path 'admin/*'.
 *       icon: The icon menu.
 *       user: The user items and links.
 *
 * Passed by reference.
 */
function groupgrade_admin_menu_output_alter(&$content) {
  $content['menu']['pla'] = array(
    '#title' => t('PLA Learning System'),
    '#href' => 'admin/pla',
    '#weight' => 10,
  );
}

function groupgrade_test_form()
{
  return '';
}

/**
 * Implement hook_form().
 *
 * Drupal needs for us to provide a form that lets the user
 * add content. This is the form that the user will see if
 * they go to node/add/node-example.
 *
 * You can get fancy with this form, or you can just punt
 * and return the default form that node_content will provide.
 */
function groupgrade_assignment_form($node, $form_state) {
  $form = array();
   $type = node_type_get_type($node);

  // We need to define form elements for the node's title and body.
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
    '#weight' => -5
  );
  // We want the body and filter elements to be adjacent. We could try doing
  // this by setting their weights, but another module might add elements to the
  // form with the same weights and end up between ours. By putting them into a
  // sub-array together, we're able force them to be rendered together.
  $form['body_filter']['body'] = array(
    '#type' => 'textarea',
    '#title' => 'Assignment Description',
    '#default_value' => '',
    '#required' => FALSE
  );
  //$form['body_filter']['filter'] = filter_form($node->format);

  // NOTE in node_example there is some addition code here not needed for this simple node-type

  return $form;
}

/**
 * Implement hook_form().
 *
 * Drupal needs for us to provide a form that lets the user
 * add content. This is the form that the user will see if
 * they go to node/add/node-example.
 *
 * You can get fancy with this form, or you can just punt
 * and return the default form that node_content will provide.
 */
function groupgrade_problem_form($node, $form_state) {
  $form = array();
   $type = node_type_get_type($node);

  // We want the body and filter elements to be adjacent. We could try doing
  // this by setting their weights, but another module might add elements to the
  // form with the same weights and end up between ours. By putting them into a
  // sub-array together, we're able force them to be rendered together.
  $form['body_filter']['body'] = array(
    '#type' => 'textarea',
    '#title' => 'Problem',
    '#default_value' => '',
    '#required' => FALSE
  );
  //$form['body_filter']['filter'] = filter_form($node->format);

  // NOTE in node_example there is some addition code here not needed for this simple node-type

  return $form;
}

/**
 * Implement hook_form().
 *
 * Drupal needs for us to provide a form that lets the user
 * add content. This is the form that the user will see if
 * they go to node/add/node-example.
 *
 * You can get fancy with this form, or you can just punt
 * and return the default form that node_content will provide.
 */
function groupgrade_solution_form($node, $form_state) {
  $form = array();
   $type = node_type_get_type($node);

  // We want the body and filter elements to be adjacent. We could try doing
  // this by setting their weights, but another module might add elements to the
  // form with the same weights and end up between ours. By putting them into a
  // sub-array together, we're able force them to be rendered together.
  $form['body_filter']['body'] = array(
    '#type' => 'textarea',
    '#title' => 'Solution',
    '#default_value' => '',
    '#required' => FALSE
  );
  //$form['body_filter']['filter'] = filter_form($node->format);

  // NOTE in node_example there is some addition code here not needed for this simple node-type

  return $form;
}

/**
 * Impliments hook_node_info()
 */
function groupgrade_node_info() {
  return array(
    'assignment' => array(
      'name' => t('Assignment'),
      'base' => 'groupgrade_assignment',
      'description' => t('An assignment for use inside of a course section.'),
      'locked' => TRUE,
    ),

    'problem' => array(
      'name' => t('Problem'),
      'base' => 'groupgrade_problem',
      'description' => t('A problem for use inside of an assignment.'),
      'locked' => TRUE,
    ),

    'solution' => array(
      'name' => t('Solution'),
      'base' => 'groupgrade_solution',
      'description' => t('A solution for use inside of an problem.'),
      'locked' => TRUE,
    ),

    'grade' => array(
      'name' => t('Grade'),
      'base' => 'groupgrade_grade',
      'description' => t('A grade for use inside of a solution.'),
      'locked' => TRUE,
    ),
  );
}

/**
 * Register the Namespaces
 * 
 * @param object
 * @access private
 */
function groupgrade_xautoload($api)
{
  $api->namespaceRoot('Drupal\\ClassLearning');
}

/**
 * Determine whether the current user has the role specified.
 *
 * @param $role_name
 *   The role required for access
 * @return bool
 *   True if the acting user has the role specified.
 */
function groupgrade_custom_access($role_name){
  $access_granted = in_array($role_name, $GLOBALS['user']->roles);
  return $access_granted;
}


/**
 * Handle a user object and retrieve the first/last name or fallback to their username
 * 
 * @param object
 * @return string
 */
function ggPrettyName($user) {
  return $user->name;
  if (count($user->field_first_name) == 0 OR count($user->field_last_name) == 0)
    return $user->name;

  return sprintf('%s %s', $user->field_first_name['und'][0]['value'], $user->field_last_name['und'][0]['value']);
}

function ldebug($exit = false) {
  var_dump(Capsule::connection()->getQueryLog());

  if ($exit) exit;
}

/**
 * Add a User to an ACL by the ACL name and User ID
 * 
 * @param string
 * @param int
 * @return void
 */
function gg_acl_add_user($acl_name, $uid = NULL, $number = NULL) {
  if ($uid == NULL) {
    global $user;
    $uid = $user->uid;
  }

  $acl_id = acl_get_id_by_name('pla', $acl_name, $number);
  
  if (! $acl_id OR $acl_id == NULL)
    $acl_id = acl_create_acl('pla', $acl_name, $number);

  acl_add_user($acl_id, $uid);
}

/**
 * Remove a User from an ACL by the ACL name and User ID
 * 
 * @param string
 * @param int
 * @return void
 */
function gg_acl_remove_user($acl_name, $uid = NULL, $number) {
  if ($uid == NULL) {
    global $user;
    $uid = $user->uid;
  }

  $acl_id = acl_get_id_by_name('pla', $acl_name, $number);
    
  // ACL doesn't exist
  if (! $acl_id OR $acl_id == NULL)
    return;

  acl_remove_user($acl_id, $uid);
}

/**
 * See if a user has any sort of instructor priviliages
 *
 * @return bool
 */
function gg_has_acl_role($role) {
  global $user;
  
  if (! $user->uid) return FALSE;

  $acl_list = acl_get_id_by_name('pla', $role);

  // List does not exist
  if ($acl_list == NULL OR ! $acl_list) return FALSE;

  if (acl_has_user($acl_list, $user->uid))
    return TRUE;
  else
    return FALSE;
}
